/** Read-only access to the backend's persistent recorded-flight archive. */
import { useCallback, useEffect, useState } from "react"
import { apiUrl } from "@/lib/api"

export interface RecordedFile {
  name: "metadata.json" | "telemetry.csv" | "events.csv" | "mission.log" | "raw.log" | string
  bytes: number
}

/**
 * What a recording IS, decided by the backend so a script reading the archive
 * and the console looking at it cannot disagree.
 *
 * `live` had a radio attached, `replay` re-ran an older raw.log, `sim` was
 * generated by fake_telemetry. This is the distinction the archive list was
 * missing entirely: `source.kind` shipped in every payload and was rendered
 * nowhere, so a replay of a simulator run looked exactly like a launch.
 */
export type ProvenanceKind = "live" | "replay" | "sim" | "unknown"

export interface Provenance {
  kind: ProvenanceKind
  /** Serial port, or the log a replay came from. May be empty. */
  detail: string
  /** Session id a replay re-ran, when it re-ran one from this archive. */
  origin: string | null
}

/**
 * One archive row. A SESSION and an operator-declared FLIGHT are the same
 * shape deliberately — a session folder holds the same five durable files, so
 * it lists, previews, downloads and deletes through the same routes. `flight`
 * is the SESSION_SELF sentinel ("-") on a session row.
 */
export interface RecordedFlight {
  session: string
  flight: string
  kind: "session" | "flight"
  /** Declared flights inside this session. Always 0 on a flight row. */
  flight_count: number
  path: string
  label: string
  /** First frame's host_time — NOT the folder's creation time; see opened_utc. */
  started_utc: string | null
  stopped_utc: string | null
  duration_s: number | null
  stop_reason: string | null
  recording: boolean
  rows: number
  events: number
  raw_bytes: number
  /** When the session folder was created. Sessions only; can precede the first frame. */
  opened_utc?: string | null
  source: Record<string, unknown>
  packet: Record<string, unknown>
  provenance: Provenance
  files: RecordedFile[]
}

interface ArchivePayload {
  root: string
  count: number
  session_count: number
  flights: RecordedFlight[]
  sessions: RecordedFlight[]
}

export interface FlightPreview {
  lines: string[]
  truncated: boolean
}

export interface TelemetryPreview {
  columns: string[]
  rows: Array<Record<string, string>>
  truncated: boolean
}

export interface RecordedFlightDetail extends RecordedFlight {
  mission: FlightPreview
  telemetry: TelemetryPreview
}

export interface DeleteResult {
  ok: boolean
  error?: string
}

export type ArchiveState = {
  status: "loading" | "ok" | "unreachable"
  data: ArchivePayload | null
  refresh: () => Promise<void>
  /**
   * Permanently delete one recorded flight folder.
   *
   * Returns the backend's refusal rather than throwing, because every refusal
   * here is something the operator needs to read: the flight is still
   * recording, or the folder holds a file this ground station did not write.
   */
  remove: (flight: RecordedFlight) => Promise<DeleteResult>
}

const ARCHIVE_POLL_MS = 5000

export function useRecordedFlights(): ArchiveState {
  const [status, setStatus] = useState<ArchiveState["status"]>("loading")
  const [data, setData] = useState<ArchivePayload | null>(null)

  const refresh = useCallback(async () => {
    try {
      const response = await fetch(apiUrl("/flights"), { cache: "no-store" })
      if (!response.ok) throw new Error(String(response.status))
      setData((await response.json()) as ArchivePayload)
      setStatus("ok")
    } catch {
      setStatus("unreachable")
    }
  }, [])

  const remove = useCallback(
    async (flight: RecordedFlight): Promise<DeleteResult> => {
      const path = `/flights/${encodeURIComponent(flight.session)}/${encodeURIComponent(flight.flight)}`
      try {
        const response = await fetch(apiUrl(path), { method: "DELETE" })
        const body = (await response.json().catch(() => ({}))) as { error?: string }
        if (!response.ok) return { ok: false, error: body.error ?? `HTTP ${response.status}` }
        // Drop it locally straight away: the 5 s poll would otherwise leave a
        // deleted flight on screen long enough to be clicked again.
        const gone = (f: RecordedFlight) =>
          f.session === flight.session && f.flight === flight.flight
        setData((prev) =>
          prev
            ? {
                ...prev,
                flights: prev.flights.filter((f) => !gone(f)),
                sessions: prev.sessions.filter((f) => !gone(f)),
                count: Math.max(0, prev.count - (flight.kind === "flight" ? 1 : 0)),
                session_count: Math.max(0, prev.session_count - (flight.kind === "session" ? 1 : 0)),
              }
            : prev,
        )
        refresh()
        return { ok: true }
      } catch {
        return { ok: false, error: "backend unreachable" }
      }
    },
    [refresh],
  )

  useEffect(() => {
    refresh()
    const id = window.setInterval(refresh, ARCHIVE_POLL_MS)
    return () => window.clearInterval(id)
  }, [refresh])

  return { status, data, refresh, remove }
}

export type DetailState = {
  status: "idle" | "loading" | "ok" | "error"
  data: RecordedFlightDetail | null
  refresh: () => Promise<void>
}

export function useRecordedFlightDetail(flight: RecordedFlight | null): DetailState {
  const [status, setStatus] = useState<DetailState["status"]>("idle")
  const [data, setData] = useState<RecordedFlightDetail | null>(null)

  const session = flight?.session ?? null
  const name = flight?.flight ?? null
  const refresh = useCallback(async () => {
    if (!session || !name) {
      setStatus("idle")
      setData(null)
      return
    }
    setStatus("loading")
    try {
      const path = `/flights/${encodeURIComponent(session)}/${encodeURIComponent(name)}`
      const response = await fetch(apiUrl(path), { cache: "no-store" })
      if (!response.ok) throw new Error(String(response.status))
      setData((await response.json()) as RecordedFlightDetail)
      setStatus("ok")
    } catch {
      setData(null)
      setStatus("error")
    }
  }, [session, name])

  useEffect(() => {
    refresh()
  }, [refresh])

  return { status, data, refresh }
}

export function recordedFlightFileUrl(flight: RecordedFlight, name: string): string {
  return apiUrl(
    `/flights/${encodeURIComponent(flight.session)}/${encodeURIComponent(flight.flight)}` +
      `/files/${encodeURIComponent(name)}`,
  )
}
